# ===== Build stage =====
FROM maven:3.9-eclipse-temurin-25 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests


# ===== Runtime stage =====
FROM eclipse-temurin:25-jre

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 80

CMD ["sh", "-c", "java -Dserver.port=${PORT:-80} -jar app.jar"]
